server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: catalog-service
  data:
    redis:
      host: localhost
      port: 6379

cache:
  products:
    ttl: 3600
  productList:
    ttl: 600
